"""update_chat_id_to_bigint

Revision ID: 5f29694862ad
Revises: 
Create Date: 2025-05-26 15:03:29.150553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f29694862ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_statistics',
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('losing_trades', sa.Integer(), nullable=False),
    sa.Column('total_profit', sa.Float(), nullable=False),
    sa.Column('total_commission', sa.Float(), nullable=False),
    sa.Column('total_swap', sa.Float(), nullable=False),
    sa.Column('max_profit', sa.Float(), nullable=True),
    sa.Column('max_loss', sa.Float(), nullable=True),
    sa.Column('average_profit', sa.Float(), nullable=True),
    sa.Column('average_loss', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('average_risk_reward', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('recovery_factor', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('stats_metadata', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_statistics_id'), 'daily_statistics', ['id'], unique=False)
    op.create_index(op.f('ix_daily_statistics_trading_date'), 'daily_statistics', ['trading_date'], unique=True)
    op.create_table('signals',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=False),
    sa.Column('signal_type', sa.Enum('MARKET', 'LIMIT', 'STOP', name='signaltype'), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.Enum('BUY', 'SELL', name='signaldirection'), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('risk_reward', sa.Float(), nullable=True),
    sa.Column('lot_size', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'DUPLICATE', 'CANCELLED', 'EXPIRED', name='signalstatus'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('original_signal_id', sa.UUID(), nullable=True),
    sa.Column('signal_metadata', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['original_signal_id'], ['signals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_channel_name'), 'signals', ['channel_name'], unique=False)
    op.create_index(op.f('ix_signals_chat_id'), 'signals', ['chat_id'], unique=False)
    op.create_index(op.f('ix_signals_id'), 'signals', ['id'], unique=False)
    op.create_index(op.f('ix_signals_is_duplicate'), 'signals', ['is_duplicate'], unique=False)
    op.create_index(op.f('ix_signals_message_id'), 'signals', ['message_id'], unique=False)
    op.create_index(op.f('ix_signals_original_signal_id'), 'signals', ['original_signal_id'], unique=False)
    op.create_index(op.f('ix_signals_status'), 'signals', ['status'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.create_table('trades',
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('mt5_ticket', sa.Integer(), nullable=False),
    sa.Column('mt5_position_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', 'STOP', 'STOP_LIMIT', name='ordertype'), nullable=False),
    sa.Column('direction', sa.Enum('BUY', 'SELL', name='signaldirection'), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('state', sa.Enum('PENDING', 'EXECUTED', 'CANCELLED', 'REJECTED', 'PARTIAL', 'EXPIRED', 'ERROR', name='tradestate'), nullable=False),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('swap', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('trade_metadata', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_mt5_position_id'), 'trades', ['mt5_position_id'], unique=False)
    op.create_index(op.f('ix_trades_mt5_ticket'), 'trades', ['mt5_ticket'], unique=True)
    op.create_index(op.f('ix_trades_signal_id'), 'trades', ['signal_id'], unique=False)
    op.create_index(op.f('ix_trades_state'), 'trades', ['state'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_state'), table_name='trades')
    op.drop_index(op.f('ix_trades_signal_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_mt5_ticket'), table_name='trades')
    op.drop_index(op.f('ix_trades_mt5_position_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index(op.f('ix_signals_status'), table_name='signals')
    op.drop_index(op.f('ix_signals_original_signal_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_message_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_is_duplicate'), table_name='signals')
    op.drop_index(op.f('ix_signals_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_chat_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_channel_name'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_daily_statistics_trading_date'), table_name='daily_statistics')
    op.drop_index(op.f('ix_daily_statistics_id'), table_name='daily_statistics')
    op.drop_table('daily_statistics')
    # ### end Alembic commands ###
