# GoldMirror Trading Configuration

# Trading Parameters
trading:
  risk_per_trade: 0.25  # Percentage of account balance
  max_open_trades: 2
  daily_loss_limit: 200  # In account currency
  cooldown_after_loss: 3600  # Seconds
  max_slippage: 5  # Points

trading_sessions:
  - name: Crypto
    start_time: "00:00"
    end_time: "23:59"
    symbols: ["BTCUSD", "ETHUSD", "LTCUSD", "XRPUSD", "BCHUSD"]
    timezone: "UTC"
    is_24_7: true  # Indicates 24/7 trading session
  - name: London
    start_time: "08:00"
    end_time: "16:00"
    symbols: ["EURUSD", "GBPUSD", "EURGBP"]
    timezone: "Europe/London"
  - name: New York
    start_time: "13:00"
    end_time: "22:00"
    symbols: ["EURUSD", "GBPUSD", "EURGBP"]
    timezone: "America/New_York"
  - name: Tokyo
    start_time: "00:00"
    end_time: "08:00"
    symbols: ["EURUSD", "GBPUSD", "EURGBP"]
    timezone: "Asia/Tokyo"

# Position Management
position:
  breakeven:
    enabled: true
    trigger_tp: 1  # Move to breakeven after TP1
    offset: 1  # Points above entry
  partial_close:
    enabled: true
    levels: [0.25, 0.25, 0.25, 0.25]  # Split position into 4 equal parts


# News Filter
news_filter:
  buffer_minutes: 30
  affected_symbols:
    EUR: ["EURUSD", "EURGBP"]
    GBP: ["GBPUSD", "EURGBP"]
    USD: ["EURUSD", "GBPUSD"]


# Signal Validation
signal:
  confidence_threshold: 0.8
  max_signal_age: 300  # Seconds
  required_fields:
    - "direction"
    - "symbol"
    - "entry"
    - "sl"
    - "tp1"
    - "tp2"
    - "tp3"
    - "tp4"

# Logging
logging:
  level: "INFO"
  format: "structured"
  file:
    enabled: true
    path: "logs/goldmirror.log"
    max_size: 10485760  # 10MB
    backup_count: 5
  telegram:
    enabled: true
    notify_on:
      - "trade_executed"
      - "tp_hit"
      - "sl_hit"
      - "breakeven"
      - "error"

# Analytics
analytics:
  enabled: false
  metrics:
    - "win_rate"
    - "profit_factor"
    - "average_win"
    - "average_loss"
    - "max_drawdown"
    - "breakeven_hit_rate"
  dashboard:
    enabled: false
    port: 8501
    host: "localhost"
    update_interval: 60  # Seconds 

mt5:
  server: "127.0.0.1"
  timezone: "UTC"

risk:
  max_daily_loss_pct: 0.02
  max_position_size_pct: 0.02
  max_open_positions: 3
  max_risk_per_trade_pct: 0.02
  min_account_balance: 10000


