# GoldMirror Trading Configuration

# Application configuration
environment: development
log_level: INFO

# Database configuration
database:
  url: postgresql+asyncpg://postgres:postgres@localhost:5432/telecopier
  pool_size: 5
  max_overflow: 10
  echo: false

# Telegram configuration
telegram:
  api_id: ${TELEGRAM_API_ID}
  api_hash: ${TELEGRAM_API_HASH}
  phone: ${TELEGRAM_PHONE}
  session_name: telecopier
  channels:
    - "your_channel_1"
    - "your_channel_2"

# MT5 configuration
mt5:
  server: ${MT5_SERVER}
  login: ${MT5_LOGIN}
  password: ${MT5_PASSWORD}
  timeout: 60000
  enable_real_trading: false

# Risk Management Parameters
risk:
  # Position Sizing
  risk_per_trade_pct: 0.02
  max_position_size_pct: 0.02
  max_open_positions: 10
  
  # Loss Limits
  max_daily_loss_pct: 0.04
  daily_loss_limit: 0.05  # Maximum daily loss in account currency
  min_account_balance: 100  # Minimum account balance required to trade
  
  # Trade Management
  cooldown_after_loss: 3600  # Seconds to wait after a loss
  max_slippage: 5  # Maximum allowed slippage in points
  position_sizing: risk_based

# Trading Sessions
trading_sessions:
  - name: Crypto
    start_time: "00:00"
    end_time: "23:59"
    symbols: ["BTCUSD", "ETHUSD", "LTCUSD", "XRPUSD", "BCHUSD"]
    timezone: "UTC"
    is_24_7: true  # Indicates 24/7 trading session
  - name: London
    start_time: "08:00"
    end_time: "16:00"
    symbols: ["EURUSD", "GBPUSD", "EURGBP", "XAUUSD", "XAGUSD"]
    timezone: "Europe/London"
  - name: New York
    start_time: "13:00"
    end_time: "22:00"
    symbols: ["EURUSD", "GBPUSD", "EURGBP", "XAUUSD", "XAGUSD"]
    timezone: "America/New_York"
  - name: Tokyo
    start_time: "00:00"
    end_time: "08:00"
    symbols: ["EURUSD", "GBPUSD", "EURGBP", "XAUUSD", "XAGUSD"]
    timezone: "Asia/Tokyo"

# Position Management
position:
  breakeven:
    enabled: true
    trigger_tp: 1  # Move to breakeven after TP1
    offset: 1  # Points above entry
  partial_close:
    enabled: true
    levels: [0.25, 0.25, 0.25, 0.25]  # Split position into 4 equal parts


# News Filter
news_filter:
  buffer_minutes: 30
  affected_symbols:
    EUR: ["EURUSD", "EURGBP"]
    GBP: ["GBPUSD", "EURGBP"]
    USD: ["EURUSD", "GBPUSD"]


# Signal Validation
signal:
  confidence_threshold: 0.8
  max_signal_age: 300  # Seconds
  required_fields:
    - "direction"
    - "symbol"
    - "entry"
    - "sl"
    - "tp1"
    - "tp2"
    - "tp3"
    - "tp4"

# Logging
logging:
  level: "INFO"
  format: "structured"
  file:
    enabled: true
    path: "logs/goldmirror.log"
    max_size: 10485760  # 10MB
    backup_count: 5
  telegram:
    enabled: true
    notify_on:
      - "trade_executed"
      - "tp_hit"
      - "sl_hit"
      - "breakeven"
      - "error"

# Analytics
analytics:
  enabled: false
  metrics:
    - "win_rate"
    - "profit_factor"
    - "average_win"
    - "average_loss"
    - "max_drawdown"
    - "breakeven_hit_rate"
  dashboard:
    enabled: false
    port: 8501
    host: "localhost"
    update_interval: 60  # Seconds 

# Redis configuration
redis:
  url: ${REDIS_URL:-redis://localhost:6379/0}  # Default if not set
  pool_size: 10
  timeout: 30
  retry_interval: 1
  max_retries: 3

# OpenAI Configuration
openai:
  model: "gpt-3.5-turbo"
  temperature: 0.0  # Use deterministic outputs
  max_tokens: 1000
  timeout_seconds: 30
  retry_attempts: 3
  retry_delay_seconds: 1


